mobs = [
    "bat",
    "blaze",
    "bogged",
    "breeze",
    "spider",
    "creaking",
    "creeper",
    "drowned",
    "guardian",
    "enderman",
    "endermite",
    "evoker",
    "ghast",
    "goat",
    "husk",
    "hoglin",
    "magma cube",
    "phantom",
    "piglin",
    "pillager",
    "pufferfish",
    "ravager",
    "shulker",
    "silverfish",
    "skeleton",
    "slime",
    "stray",
    "vex",
    "vindicator",
    "warden",
    "witch",
    "zoglin",
    "zombie",
]

allowed_mobs = [
    "allay",
    "armadillo",
    "axolotl",
    "bee",
    "camel",
    "cat",
    "chicken",
    "cod",
    "copper golem",
    "iron golem",
    "happy_ghast",
    "horse",
    "cow",
    "dolphin",
    "donkey",
    "fox",
    "frog",
    "squid",
    "rabbit",
    "polar bear",
    "pig",
    "parrot",
    "panda",
    "ocelot",
    "mule",
    "mooshroom",
    "llama",
    "salmon",
    "sheep",
    "sniffer",
    "snow golem",
    "strider",
    "tadpole",
    "tropical_fish",
    "turtle",
    "villager",
    "wandering trader",
    "wolf",
    "zombie horse"
]